Add Lucide to Icons
codu-code/free-developer-resources pull request #49
Opened 2024-12-12 15:34 UTC by EmanuelR0sa

## Fixes Issue

## Changes proposed

Add [Lucide icons](https://lucide.dev/icons)  to the Icons List.

## Check List (Check all the applicable boxes) 

- [ ] Addresses an existing open issue: Closes #000
- [x] The title of my pull request is a short description of the requested changes.
- [x] I followed the [Contributing Guidelines](https://github.com/codu-code/codu/blob/develop/CONTRIBUTING.md) 

## Screenshots

## Note to reviewers

2025-01-05 22:59 UTC, scaulfield7 requested changes

2025-01-05 22:59 UTC, scaulfield7 commented on README.md
> +| [Lucide](https://lucide.dev/)                      | Beautiful & consistent icon toolkit made by the community.
Hey Emanuel! Your change here on line 236 looks good to me. However about 300 other lines have code have been changed, possibly automatically with some formatting your code editor did when you saved the file. It would be best to add your update only changing the line you added at line 236 rather than modifying the other lines too.

2025-01-06 09:01 UTC, EmanuelR0sa commented on README.md
> +| [Lucide](https://lucide.dev/)                      | Beautiful & consistent icon toolkit made by the community.
hey Scaul! I will make the changes and submit it again

2025-01-06 09:52 UTC, scaulfield7 commented on README.md
> +| [Lucide](https://lucide.dev/)                      | Beautiful & consistent icon toolkit made by the community.
Thanks Emanuel, good shout! Have approved the new PR now so this one can be closed.

2025-01-06 09:54 UTC, closed without merging